
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Presentation about Sarva Bio Remed Products"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true